/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jeremyvalenzuela' at '6/19/16 1:29 AM' with Gradle 2.14
 *
 * @author jeremyvalenzuela, @date 6/19/16 1:29 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
